# =============================================================================
# КОНФИГУРАЦИЯ МАППИНГА КАТЕГОРИЙ ДЛЯ 2shark
# =============================================================================
#
# Этот файл определяет как технологии (папки с документацией) 
# соотносятся с основными категориями в базе данных.
#
# НАЗНАЧЕНИЕ:
# - Автоматическая категоризация документов при сканировании
# - Определение приоритетов для сортировки
# - Добавление описаний для подкатегорий
# - Поддержка документов в нескольких категориях
#
# СТРУКТУРА ФАЙЛА:
# Подкатегория:
#   technology: ОсновнаяКатегория или [Категория1, Категория2]
#   priority: число (меньше = выше приоритет)
#   description: Описание технологии
#
# ПРИМЕРЫ:
# - Одиночная категория: technology: Frontend
# - Множественные категории: technology: Frontend,Backend
# - Приоритеты: 1 = самый высокий, 10 = самый низкий
#
# ПОДДЕРЖИВАЕМЫЕ КАТЕГОРИИ:
# - Frontend: Веб-разработка, UI/UX, браузерные технологии
# - Backend: Серверная разработка, API, базы данных
#
# =============================================================================

# =============================================================================
# FRONTEND КАТЕГОРИИ
# =============================================================================

HTML:
  technology: Frontend
  priority: 1
  description: Язык разметки гипертекста

CSS:
  technology: Frontend
  priority: 2
  description: Каскадные таблицы стилей

JSCore:
  technology: Frontend
  priority: 3
  description: Основы JavaScript

State Managers:
  technology: Frontend
  priority: 4
  description: Управление состоянием в React приложениях

ReactCore:
  technology: Frontend
  priority: 5
  description: Основы React

TypeScript:
  technology: Frontend
  priority: 6
  description: Типизированный JavaScript

Next.js:
  technology: Frontend
  priority: 7
  description: React фреймворк

Jest, RTL:
  technology: Frontend
  priority: 8
  description: Тестирование React приложений

# =============================================================================
# BACKEND КАТЕГОРИИ
# =============================================================================

Node.js:
  technology: Backend
  priority: 1
  description: JavaScript runtime для сервера

Java:
  technology: Backend
  priority: 2
  description: Серверный язык программирования

# =============================================================================
# УНИВЕРСАЛЬНЫЕ КАТЕГОРИИ (Frontend + Backend)
# =============================================================================
# Технологии, которые могут быть в нескольких специальностях

Git:
  technology: Frontend,Backend
  priority: 1
  description: Система контроля версий

Browser:
  technology: Frontend,Backend
  priority: 2
  description: Браузерное окружение

Patterns:
  technology: Frontend,Backend
  priority: 3
  description: Паттерны программирования

SQL:
  technology: Frontend,Backend
  priority: 4
  description: Работа с базами данных
