# =============================================================================
# КОНФИГУРАЦИЯ МАППИНГА ТЕХНОЛОГИЙ ДЛЯ 2shark
# =============================================================================
#
# Этот файл определяет как технологии (папки с документацией) 
# соотносятся с основными специальностями в базе данных.
#
# НАЗНАЧЕНИЕ:
# - Автоматическая категоризация документов при сканировании
# - Определение приоритетов для сортировки
# - Добавление описаний для подкатегорий
# - Поддержка документов в нескольких категориях
#
# СТРУКТУРА ФАЙЛА:
# Технология:
#   specialty: ОсновнаяСпециальность или [Специальность1, Специальность2]
#   priority: число (меньше = выше приоритет)
#   description: Описание технологии
#
# ПРИМЕРЫ:
# - Одиночная специальность: specialty: Frontend
# - Множественные специальности: specialty: Frontend,Backend
# - Приоритеты: 1 = самый высокий, 10 = самый низкий
#
# ПОДДЕРЖИВАЕМЫЕ КАТЕГОРИИ:
# - Frontend: Веб-разработка, UI/UX, браузерные технологии
# - Backend: Серверная разработка, API, базы данных
#
# =============================================================================

# =============================================================================
# FRONTEND КАТЕГОРИИ
# =============================================================================

HTML:
  specialty: Frontend
  priority: 1
  description: Язык разметки гипертекста

CSS:
  specialty: Frontend
  priority: 2
  description: Каскадные таблицы стилей

JSCore:
  specialty: Frontend
  priority: 3
  description: Основы JavaScript

State Managers:
  specialty: Frontend
  priority: 4
  description: Управление состоянием в React приложениях

ReactCore:
  specialty: Frontend
  priority: 5
  description: Основы React

TypeScript:
  specialty: Frontend
  priority: 6
  description: Типизированный JavaScript

Next.js:
  specialty: Frontend
  priority: 7
  description: React фреймворк

Jest, RTL:
  specialty: Frontend
  priority: 8
  description: Тестирование React приложений

# =============================================================================
# BACKEND КАТЕГОРИИ
# =============================================================================

Node.js:
  specialty: Backend
  priority: 1
  description: JavaScript runtime для сервера

Java:
  specialty: Backend
  priority: 2
  description: Серверный язык программирования

# =============================================================================
# УНИВЕРСАЛЬНЫЕ КАТЕГОРИИ (Frontend + Backend)
# =============================================================================
# Технологии, которые могут быть в нескольких специальностях

Git:
  specialty: Frontend,Backend
  priority: 1
  description: Система контроля версий

Браузерное окружение:
  specialty: Frontend,Backend
  priority: 2
  description: Браузерное окружение

Патерны:
  specialty: Frontend,Backend
  priority: 3
  description: Паттерны программирования

SQL:
  specialty: Frontend,Backend
  priority: 4
  description: Работа с базами данных
