import { SCHEMA } from '../../../schema';

export const deletes: string[] = [
    SCHEMA.DELETE_ARTICLE_TAGS_DATA_QUERY,
    SCHEMA.DELETE_TAGS_DATA_QUERY,
    SCHEMA.DELETE_ARTICLES_DATA_QUERY,
    SCHEMA.DELETE_TECHNOLOGIES_DATA_QUERY,
    SCHEMA.DELETE_SPECIALTIES_DATA_QUERY,
  ];
